parameters:
  - name: name
    type: string
  - name: displayName
    type: string
  - name: environment
    type: string
  - name: artifactName
    type: string
  - name: condition
    type: string

stages:
  - stage: ${{ parameters.name }}
    dependsOn: BuildPackage
    displayName: ${{ parameters.displayName }}
    condition: and(succeeded(), ${{ parameters.condition }})
    variables:
      - group: B2CClient-Common
      - ${{ if eq(parameters.environment, 'prd') }}:
        - group: B2CClient-Prod
      - ${{ if eq(parameters.environment, 'stg') }}:
        - group: B2CClient-Staging
      - ${{ if eq(parameters.environment, 'dev') }}:
        - group: B2CClient-Dev
      - name: environment
        value: "${{ parameters.environment }}"
      - name: b2cTemplatePath
        value: "$(Pipeline.Workspace)/${{ parameters.artifactName }}/templates"

    jobs:
      - deployment: DeployStorageAccount
        displayName: "Deploy Storage Account ${{ parameters.environment }}"
        environment: ${{ parameters.environment }}
        pool:
          vmImage: "windows-latest"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFileCopy@5
                  inputs:
                    SourcePath: $(b2cTemplatePath)
                    azureSubscription:  $(ServicePrincipalName)
                    Destination: "AzureBlob"
                    storage: "$(ApplicationName)$(environment)st"
                    ContainerName: "templates"
                    resourceGroup: $(resourceGroupName)
                    AdditionalArgumentsForBlobCopy: |
                      --overwrite=true `
                      --recursive=true 
