name: "$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)"

trigger:
  branches:
    include:
      - main
  tags:
    include:
      - b2c-*
  paths:
    include:
      - Azure/Infra-as-code/*
      - Azure/Pipelines/*

variables:
  - group: B2CClient-Common
  - name: artifactName
    value: "client"
  - ${{ if and(eq(variables['BUILD_ENV'], ''), startsWith(variables['build.sourceBranch'], 'refs/tags/')) }}:
      - name: BUILD_ENV
        value: "prd"
      - group: B2CClient-Prod

  - ${{ if eq(variables['BUILD_ENV'], '') }}:
      - name: BUILD_ENV
        value: "dev"
      - group: B2CClient-Dev

stages:
  - template: "/Azure/Pipelines/infra-pipeline/build-stage.yml"
    parameters:
      artifactName: ${{ variables.artifactName }}

  - template: "/Azure/Pipelines/infra-pipeline/deploy-stage.yml"
    parameters:
      name: "B2CInfraDev"
      displayName: "Create B2C Infra Dev"
      artifactName: ${{ variables.artifactName }}
      environment: ${{ variables.BUILD_ENV }}
      condition: "eq(variables['build.sourceBranch'], 'refs/heads/main')"
  
  - template: "/Azure/Pipelines/infra-pipeline/deploy-stage.yml"
    parameters:
      name: "B2CInfraProduction"
      displayName: "Create B2C Infra Production"
      artifactName: ${{ variables.artifactName }}
      environment: ${{ variables.BUILD_ENV }}
      condition: "startsWith(variables['build.sourceBranch'], 'refs/tags/')"
